### ISSUE TITLE
Multi Column Sorting

### ISSUE THREAD

**Issue by miseeger** [jbaysolutions/vue-bootstrap-table#10]
Hi, just came around and noticed your component. I'd like to suggest the implementation of multi column sort functionality. A feature which I often miss in table components.

**Comment by syshex** [comment]
I'll add this to my list.

**Comment by miseeger** [comment]
Sounds great 👍 

Your table component looks **very** promising and may be the one I was searching for 😄 Will have a closer look!

**Comment by syshex** [comment]
I was looking into this and shouldn't be a problem to get this going.
MultiColumn sort will be a configurable option , and if enabled, multiple columns can be selected through the use of Shift+Click .

This will however break the existing Ajax functionality, which is now only sending one Column to the server for sorting. This will also be fixed.

Implementation should be quite fast for Vue2 Impl [jbaysolutions/vue2-bootstrap-table](https://github.com/jbaysolutions/vue2-bootstrap-table) where we are using lodash for this. For Vue1 (this one) , I'll rewrite this bit to also use lodash instead of Vue filters, so progress on both libs can be made easier.

**Comment by miseeger** [comment]
You're just awesome! Looking forward for this feature 😄

**Comment by syshex** [comment]
Something like this, yes ?

![multicolumn_select](https://cloud.githubusercontent.com/assets/4295520/26717417/4406147e-4775-11e7-9895-4f59a2146dcb.gif)

**Comment by syshex** [comment]
Added on 1.1.2
For Vue2 : [jbaysolutions/vue2-bootstrap-table](https://github.com/jbaysolutions/vue2-bootstrap-table)

**Comment by miseeger** [comment]
Yeah !!! Plus 💯 - Thank you very much !!!

**Comment by syshex** [comment]
No problem. If you find any issues with it, let me know.

**Comment by miseeger** [comment]
VueJS is one of my great favorites but I cannot use it for daily business work, yet. So I'm going to use it in private projects. My goal is rather to contribute with additional features than suggesting new ones 😉 I'm not that familiar writing components for Vue despite of having written a paginator myself. It's the lack of time and lack of usage for my daily work. I hope to change this soon, so that I'm really able to contribute to vue2-bootstrap-table in the future ...
